
const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0020[   6] = { /* code 0020 */
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0021[   6] = { /* code 0021 */
  0x90,  0x24,  0x49,  0x10,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0022[   9] = { /* code 0022 */
  0x40,  0x29,  0x05,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0023[  14] = { /* code 0023 */
  0x00,  0x08,  0x28,  0xFE,  0x24,  0x24,  0x7F,  0x14,
  0x14,  0x10,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0024[  13] = { /* code 0024 */
  0x08,  0x8E,  0x42,  0xA1,  0x60,  0xE0,  0x50,  0x28,
  0x0F,  0x02,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0025[  20] = { /* code 0025 */
  0x00,  0x70,  0x84,  0x24,  0xA4,  0x20,  0x3D,  0x39,
  0x79,  0x09,  0x4A,  0x48,  0x42,  0x1C,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0026[  16] = { /* code 0026 */
  0x00,  0x38,  0x90,  0x20,  0x41,  0x81,  0x81,  0x04,
  0x51,  0x42,  0x78,  0x01,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0027[   4] = { /* code 0027 */
  0xA8,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0028[   7] = { /* code 0028 */
  0x40,  0x24,  0x22,  0x22,  0x22,  0x42,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0029[   7] = { /* code 0029 */
  0x20,  0x42,  0x44,  0x44,  0x44,  0x22,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_002A[  13] = { /* code 002A */
  0x08,  0x84,  0x0F,  0x41,  0xA1,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_002B[  13] = { /* code 002B */
  0x00,  0x00,  0x02,  0x81,  0xF8,  0x23,  0x10,  0x08,
  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_002C[   6] = { /* code 002C */
  0x00,  0x00,  0x00,  0x92,  0x02,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_002D[   7] = { /* code 002D */
  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_002E[   6] = { /* code 002E */
  0x00,  0x00,  0x00,  0x10,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_002F[   7] = { /* code 002F */
  0x80,  0x48,  0x24,  0x22,  0x11,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0030[  13] = { /* code 0030 */
  0x00,  0x8E,  0x48,  0x24,  0x12,  0x89,  0x44,  0x22,
  0x0E,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0031[  13] = { /* code 0031 */
  0x00,  0x84,  0x03,  0x81,  0x40,  0x20,  0x10,  0x08,
  0x04,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0032[  13] = { /* code 0032 */
  0x00,  0x8E,  0x08,  0x04,  0x82,  0x20,  0x08,  0x02,
  0x1F,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0033[  13] = { /* code 0033 */
  0x00,  0x8E,  0x08,  0x04,  0xE3,  0x80,  0x40,  0x20,
  0x0F,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0034[  13] = { /* code 0034 */
  0x00,  0x08,  0x0A,  0x45,  0x12,  0x89,  0xFE,  0x20,
  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0035[  13] = { /* code 0035 */
  0x00,  0x9F,  0x40,  0x20,  0xF0,  0x80,  0x40,  0x20,
  0x0F,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0036[  13] = { /* code 0036 */
  0x00,  0x1C,  0x41,  0xE0,  0x11,  0x89,  0x44,  0x22,
  0x0E,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0037[  13] = { /* code 0037 */
  0x00,  0x1F,  0x08,  0x04,  0x81,  0x20,  0x10,  0x08,
  0x02,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0038[  13] = { /* code 0038 */
  0x00,  0x8E,  0x48,  0x64,  0x63,  0xC8,  0x44,  0x22,
  0x0E,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0039[  13] = { /* code 0039 */
  0x00,  0x8E,  0x48,  0x24,  0x12,  0xF1,  0x40,  0x10,
  0x07,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_003A[   6] = { /* code 003A */
  0x00,  0x04,  0x00,  0x10,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_003B[   6] = { /* code 003B */
  0x00,  0x04,  0x00,  0x92,  0x02,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_003C[  13] = { /* code 003C */
  0x00,  0x00,  0x08,  0x43,  0x30,  0x60,  0x40,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_003D[  13] = { /* code 003D */
  0x00,  0x00,  0x00,  0xE0,  0x03,  0xF8,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_003E[  13] = { /* code 003E */
  0x00,  0x80,  0x80,  0x01,  0x81,  0x31,  0x04,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_003F[   9] = { /* code 003F */
  0xC0,  0x41,  0x88,  0x10,  0x01,  0x80,  0x00,  0x00,
  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0040[  21] = { /* code 0040 */
  0x00,  0x80,  0x1F,  0x04,  0x22,  0x4E,  0x92,  0xA4,
  0x48,  0x8A,  0xA4,  0x48,  0x72,  0x43,  0x00,  0xF8,
  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0041[  14] = { /* code 0041 */
  0x00,  0x00,  0x18,  0x18,  0x24,  0x24,  0x7E,  0x42,
  0x42,  0x81,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0042[  14] = { /* code 0042 */
  0x00,  0x3E,  0x42,  0x42,  0x42,  0x3E,  0x42,  0x42,
  0x42,  0x3E,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0043[  14] = { /* code 0043 */
  0x00,  0x78,  0x04,  0x02,  0x02,  0x02,  0x02,  0x02,
  0x04,  0x78,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0044[  16] = { /* code 0044 */
  0x00,  0x7C,  0x08,  0x11,  0x24,  0x48,  0x90,  0x20,
  0x41,  0x42,  0x7C,  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0045[  13] = { /* code 0045 */
  0x00,  0x9F,  0x40,  0x20,  0xF0,  0x09,  0x04,  0x02,
  0x1F,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0046[  13] = { /* code 0046 */
  0x00,  0xBF,  0x40,  0x20,  0xF0,  0x0B,  0x04,  0x02,
  0x01,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0047[  16] = { /* code 0047 */
  0x00,  0xF0,  0x10,  0x12,  0x20,  0x40,  0x9C,  0x20,
  0x41,  0x84,  0xF0,  0x01,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0048[  16] = { /* code 0048 */
  0x00,  0x04,  0x09,  0x12,  0x24,  0xC8,  0x9F,  0x20,
  0x41,  0x82,  0x04,  0x01,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0049[   6] = { /* code 0049 */
  0x90,  0x24,  0x49,  0x12,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_004A[  11] = { /* code 004A */
  0x00,  0x82,  0x20,  0x08,  0x82,  0x20,  0x08,  0x82,
  0x18,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_004B[  14] = { /* code 004B */
  0x00,  0x42,  0x22,  0x12,  0x0A,  0x16,  0x12,  0x22,
  0x42,  0x82,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_004C[  13] = { /* code 004C */
  0x00,  0x81,  0x40,  0x20,  0x10,  0x08,  0x04,  0x02,
  0x3F,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_004D[  20] = { /* code 004D */
  0x00,  0x10,  0x90,  0xC1,  0x0C,  0xA6,  0x28,  0x45,
  0x49,  0x49,  0x4A,  0x52,  0x12,  0x11,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_004E[  16] = { /* code 004E */
  0x00,  0x04,  0x19,  0x52,  0xA4,  0x48,  0x92,  0x28,
  0x51,  0xC2,  0x04,  0x01,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_004F[  18] = { /* code 004F */
  0x00,  0xE0,  0x41,  0x88,  0x40,  0x02,  0x09,  0x24,
  0x90,  0x40,  0x84,  0xE0,  0x01,  0x00,  0x00,  0x00,
  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0050[  14] = { /* code 0050 */
  0x00,  0x3E,  0x42,  0x42,  0x42,  0x42,  0x3E,  0x02,
  0x02,  0x02,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0051[  18] = { /* code 0051 */
  0x00,  0xE0,  0x41,  0x88,  0x40,  0x02,  0x09,  0x24,
  0x90,  0x40,  0x84,  0xE0,  0x01,  0x04,  0x20,  0x00,
  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0052[  14] = { /* code 0052 */
  0x00,  0x3E,  0x42,  0x42,  0x42,  0x3E,  0x22,  0x22,
  0x42,  0x42,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0053[  13] = { /* code 0053 */
  0x00,  0x9E,  0x40,  0x20,  0xE0,  0x80,  0x40,  0x20,
  0x0F,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0054[  13] = { /* code 0054 */
  0x80,  0x3F,  0x02,  0x81,  0x40,  0x20,  0x10,  0x08,
  0x04,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0055[  16] = { /* code 0055 */
  0x00,  0x04,  0x09,  0x12,  0x24,  0x48,  0x90,  0x20,
  0x41,  0x44,  0x78,  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0056[  14] = { /* code 0056 */
  0x00,  0x81,  0x81,  0x42,  0x42,  0x24,  0x24,  0x18,
  0x18,  0x08,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0057[  21] = { /* code 0057 */
  0x00,  0x10,  0x82,  0x62,  0x24,  0x46,  0x92,  0x24,
  0x49,  0x94,  0xC2,  0x30,  0x08,  0x81,  0x10,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0058[  13] = { /* code 0058 */
  0x80,  0xA0,  0x88,  0x42,  0x41,  0x50,  0x28,  0xA2,
  0x20,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0059[  13] = { /* code 0059 */
  0x80,  0xA0,  0x48,  0x44,  0xA1,  0x20,  0x10,  0x08,
  0x04,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_005A[  13] = { /* code 005A */
  0x00,  0x1F,  0x08,  0x02,  0x41,  0x10,  0x08,  0x82,
  0x3F,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_005B[   7] = { /* code 005B */
  0xE0,  0x22,  0x22,  0x22,  0x22,  0xE2,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_005C[   7] = { /* code 005C */
  0x10,  0x21,  0x22,  0x44,  0x88,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_005D[   7] = { /* code 005D */
  0x70,  0x44,  0x44,  0x44,  0x44,  0x74,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_005E[  13] = { /* code 005E */
  0x00,  0x04,  0x85,  0x22,  0x12,  0x01,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_005F[   9] = { /* code 005F */
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x80,  0x0F,
  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0060[  14] = { /* code 0060 */
  0x08,  0x10,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0061[  13] = { /* code 0061 */
  0x00,  0x00,  0x80,  0x03,  0x02,  0xF1,  0x44,  0x22,
  0x1F,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0062[  14] = { /* code 0062 */
  0x02,  0x02,  0x02,  0x3E,  0x42,  0x42,  0x42,  0x42,
  0x42,  0x3E,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0063[  11] = { /* code 0063 */
  0x00,  0x00,  0x70,  0x82,  0x20,  0x08,  0x02,  0x07,
  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0064[  14] = { /* code 0064 */
  0x40,  0x40,  0x40,  0x7C,  0x42,  0x42,  0x42,  0x42,
  0x42,  0x7C,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0065[  13] = { /* code 0065 */
  0x00,  0x00,  0x80,  0x23,  0x12,  0xF9,  0x04,  0x02,
  0x1E,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0066[   9] = { /* code 0066 */
  0x5C,  0x88,  0x27,  0x84,  0x10,  0x42,  0x00,  0x00,
  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0067[  13] = { /* code 0067 */
  0x00,  0x00,  0x80,  0x2F,  0x12,  0x89,  0x38,  0x02,
  0x5F,  0x30,  0xE8,  0x03,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0068[  14] = { /* code 0068 */
  0x02,  0x02,  0x02,  0x3E,  0x46,  0x42,  0x42,  0x42,
  0x42,  0x42,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0069[   6] = { /* code 0069 */
  0x10,  0x24,  0x49,  0x12,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_006A[   7] = { /* code 006A */
  0x40,  0x40,  0x44,  0x44,  0x44,  0x44,  0x03
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_006B[  11] = { /* code 006B */
  0x82,  0x20,  0x48,  0x92,  0xE2,  0x28,  0x92,  0x08,
  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_006C[   6] = { /* code 006C */
  0x92,  0x24,  0x49,  0x12,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_006D[  20] = { /* code 006D */
  0x00,  0x00,  0x00,  0x00,  0xBC,  0x23,  0x22,  0x11,
  0x89,  0x48,  0x44,  0x22,  0x12,  0x11,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_006E[  14] = { /* code 006E */
  0x00,  0x00,  0x00,  0x3E,  0x46,  0x42,  0x42,  0x42,
  0x42,  0x42,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_006F[  14] = { /* code 006F */
  0x00,  0x00,  0x00,  0x3C,  0x42,  0x42,  0x42,  0x42,
  0x42,  0x3C,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0070[  14] = { /* code 0070 */
  0x00,  0x00,  0x00,  0x3E,  0x42,  0x42,  0x42,  0x42,
  0x42,  0x3E,  0x02,  0x02,  0x02,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0071[  14] = { /* code 0071 */
  0x00,  0x00,  0x00,  0x7C,  0x42,  0x42,  0x42,  0x42,
  0x42,  0x7C,  0x40,  0x40,  0x40,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0072[   9] = { /* code 0072 */
  0x00,  0x00,  0x2F,  0x84,  0x10,  0x42,  0x00,  0x00,
  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0073[  11] = { /* code 0073 */
  0x00,  0x00,  0x78,  0x82,  0xC0,  0x40,  0x90,  0x07,
  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0074[   7] = { /* code 0074 */
  0x20,  0xF2,  0x22,  0x22,  0xE2,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0075[  14] = { /* code 0075 */
  0x00,  0x00,  0x00,  0x42,  0x42,  0x42,  0x42,  0x42,
  0x62,  0x7C,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0076[  11] = { /* code 0076 */
  0x00,  0x00,  0x84,  0xA1,  0x24,  0x31,  0x0C,  0x03,
  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0077[  16] = { /* code 0077 */
  0x00,  0x00,  0x00,  0x88,  0x18,  0x51,  0x95,  0x2A,
  0x55,  0x46,  0x88,  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0078[  11] = { /* code 0078 */
  0x00,  0x00,  0x48,  0x12,  0x43,  0x30,  0x52,  0x04,
  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_0079[  11] = { /* code 0079 */
  0x00,  0x00,  0x84,  0xA1,  0x24,  0x29,  0x0C,  0x41,
  0x10,  0x03,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_007A[  11] = { /* code 007A */
  0x00,  0x00,  0x78,  0x10,  0x42,  0x10,  0x82,  0x07,
  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_007B[   9] = { /* code 007B */
  0x00,  0x13,  0x42,  0xC8,  0x20,  0x84,  0x10,  0x0C,
  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_007C[  13] = { /* code 007C */
  0x08,  0x04,  0x02,  0x81,  0x40,  0x20,  0x10,  0x08,
  0x04,  0x02,  0x81,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_007D[   9] = { /* code 007D */
  0x60,  0x10,  0x42,  0x08,  0x26,  0x84,  0x90,  0x01,
  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_007E[  13] = { /* code 007E */
  0x00,  0x00,  0x00,  0x60,  0xC0,  0x01,  0x00,  0x00,
  0x00,  0x00,  0x00,  0x00,  0x00
};

const unsigned char bitmapOPEN_SANS_LIGHT_13PX_007F[  14] = { /* code 007F */
  0x00,  0x7E,  0x42,  0x42,  0x42,  0x42,  0x42,  0x42,
  0x42,  0x7E,  0x00,  0x00,  0x00,  0x00
};

const bagl_font_character_t charactersOPEN_SANS_LIGHT_13PX[96] = {
   {   3,   6, bitmapOPEN_SANS_LIGHT_13PX_0020 }, /* code 0020 */
   {   3,   6, bitmapOPEN_SANS_LIGHT_13PX_0021 }, /* code 0021 */
   {   5,   9, bitmapOPEN_SANS_LIGHT_13PX_0022 }, /* code 0022 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0023 }, /* code 0023 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0024 }, /* code 0024 */
   {  11,  20, bitmapOPEN_SANS_LIGHT_13PX_0025 }, /* code 0025 */
   {   9,  16, bitmapOPEN_SANS_LIGHT_13PX_0026 }, /* code 0026 */
   {   2,   4, bitmapOPEN_SANS_LIGHT_13PX_0027 }, /* code 0027 */
   {   4,   7, bitmapOPEN_SANS_LIGHT_13PX_0028 }, /* code 0028 */
   {   4,   7, bitmapOPEN_SANS_LIGHT_13PX_0029 }, /* code 0029 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_002A }, /* code 002A */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_002B }, /* code 002B */
   {   3,   6, bitmapOPEN_SANS_LIGHT_13PX_002C }, /* code 002C */
   {   4,   7, bitmapOPEN_SANS_LIGHT_13PX_002D }, /* code 002D */
   {   3,   6, bitmapOPEN_SANS_LIGHT_13PX_002E }, /* code 002E */
   {   4,   7, bitmapOPEN_SANS_LIGHT_13PX_002F }, /* code 002F */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0030 }, /* code 0030 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0031 }, /* code 0031 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0032 }, /* code 0032 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0033 }, /* code 0033 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0034 }, /* code 0034 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0035 }, /* code 0035 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0036 }, /* code 0036 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0037 }, /* code 0037 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0038 }, /* code 0038 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0039 }, /* code 0039 */
   {   3,   6, bitmapOPEN_SANS_LIGHT_13PX_003A }, /* code 003A */
   {   3,   6, bitmapOPEN_SANS_LIGHT_13PX_003B }, /* code 003B */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_003C }, /* code 003C */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_003D }, /* code 003D */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_003E }, /* code 003E */
   {   5,   9, bitmapOPEN_SANS_LIGHT_13PX_003F }, /* code 003F */
   {  12,  21, bitmapOPEN_SANS_LIGHT_13PX_0040 }, /* code 0040 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0041 }, /* code 0041 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0042 }, /* code 0042 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0043 }, /* code 0043 */
   {   9,  16, bitmapOPEN_SANS_LIGHT_13PX_0044 }, /* code 0044 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0045 }, /* code 0045 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0046 }, /* code 0046 */
   {   9,  16, bitmapOPEN_SANS_LIGHT_13PX_0047 }, /* code 0047 */
   {   9,  16, bitmapOPEN_SANS_LIGHT_13PX_0048 }, /* code 0048 */
   {   3,   6, bitmapOPEN_SANS_LIGHT_13PX_0049 }, /* code 0049 */
   {   6,  11, bitmapOPEN_SANS_LIGHT_13PX_004A }, /* code 004A */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_004B }, /* code 004B */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_004C }, /* code 004C */
   {  11,  20, bitmapOPEN_SANS_LIGHT_13PX_004D }, /* code 004D */
   {   9,  16, bitmapOPEN_SANS_LIGHT_13PX_004E }, /* code 004E */
   {  10,  18, bitmapOPEN_SANS_LIGHT_13PX_004F }, /* code 004F */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0050 }, /* code 0050 */
   {  10,  18, bitmapOPEN_SANS_LIGHT_13PX_0051 }, /* code 0051 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0052 }, /* code 0052 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0053 }, /* code 0053 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0054 }, /* code 0054 */
   {   9,  16, bitmapOPEN_SANS_LIGHT_13PX_0055 }, /* code 0055 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0056 }, /* code 0056 */
   {  12,  21, bitmapOPEN_SANS_LIGHT_13PX_0057 }, /* code 0057 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0058 }, /* code 0058 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0059 }, /* code 0059 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_005A }, /* code 005A */
   {   4,   7, bitmapOPEN_SANS_LIGHT_13PX_005B }, /* code 005B */
   {   4,   7, bitmapOPEN_SANS_LIGHT_13PX_005C }, /* code 005C */
   {   4,   7, bitmapOPEN_SANS_LIGHT_13PX_005D }, /* code 005D */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_005E }, /* code 005E */
   {   5,   9, bitmapOPEN_SANS_LIGHT_13PX_005F }, /* code 005F */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0060 }, /* code 0060 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0061 }, /* code 0061 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0062 }, /* code 0062 */
   {   6,  11, bitmapOPEN_SANS_LIGHT_13PX_0063 }, /* code 0063 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0064 }, /* code 0064 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0065 }, /* code 0065 */
   {   5,   9, bitmapOPEN_SANS_LIGHT_13PX_0066 }, /* code 0066 */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_0067 }, /* code 0067 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0068 }, /* code 0068 */
   {   3,   6, bitmapOPEN_SANS_LIGHT_13PX_0069 }, /* code 0069 */
   {   4,   7, bitmapOPEN_SANS_LIGHT_13PX_006A }, /* code 006A */
   {   6,  11, bitmapOPEN_SANS_LIGHT_13PX_006B }, /* code 006B */
   {   3,   6, bitmapOPEN_SANS_LIGHT_13PX_006C }, /* code 006C */
   {  11,  20, bitmapOPEN_SANS_LIGHT_13PX_006D }, /* code 006D */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_006E }, /* code 006E */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_006F }, /* code 006F */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0070 }, /* code 0070 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0071 }, /* code 0071 */
   {   5,   9, bitmapOPEN_SANS_LIGHT_13PX_0072 }, /* code 0072 */
   {   6,  11, bitmapOPEN_SANS_LIGHT_13PX_0073 }, /* code 0073 */
   {   4,   7, bitmapOPEN_SANS_LIGHT_13PX_0074 }, /* code 0074 */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_0075 }, /* code 0075 */
   {   6,  11, bitmapOPEN_SANS_LIGHT_13PX_0076 }, /* code 0076 */
   {   9,  16, bitmapOPEN_SANS_LIGHT_13PX_0077 }, /* code 0077 */
   {   6,  11, bitmapOPEN_SANS_LIGHT_13PX_0078 }, /* code 0078 */
   {   6,  11, bitmapOPEN_SANS_LIGHT_13PX_0079 }, /* code 0079 */
   {   6,  11, bitmapOPEN_SANS_LIGHT_13PX_007A }, /* code 007A */
   {   5,   9, bitmapOPEN_SANS_LIGHT_13PX_007B }, /* code 007B */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_007C }, /* code 007C */
   {   5,   9, bitmapOPEN_SANS_LIGHT_13PX_007D }, /* code 007D */
   {   7,  13, bitmapOPEN_SANS_LIGHT_13PX_007E }, /* code 007E */
   {   8,  14, bitmapOPEN_SANS_LIGHT_13PX_007F }  /* code 007F */
};

const bagl_font_t fontOPEN_SANS_LIGHT_13PX = {
   14 , /* font height in pixels   */
   10 , /* font ascent (baseline) in pixels  */
   0, /* kerning */
   0x0020, /* first character */
   0x007F, /* last character  */
   &charactersOPEN_SANS_LIGHT_13PX 
};
